### ISSUE TITLE
팀 빌딩을 위한 에세이 작성 #1. 왜 이 비즈니스를 시작했는가?

### ISSUE THREAD

**Issue by DaylightOwl** [LikeStyle-CultureArchitect/Planning#10]
### 첫 에세이 주제
왜 이 비즈니스를 시작하게 되었는지, 혹은 왜 이 비즈니스를 하고 싶은지

### 작성중 글감 부족시 아래 질문 참조
- 현재 하고 있는 일에 대한 문제의식
- 팀에 합류할 시점에 내 삶의 맥락
- 어떤 일을 할 때 행복한 지
- 이 비즈니스와 내 가치와의 연관성
- 이 비즈니스가 앞으로 어떻게 될 것 같은 지
- 같은 시대를 살아가는 사람들/또는 세상에 입장

### 이 작업을 하는 까닭
- 우리가 하는 일에는 우리의 가치가 담기기 마련
- 무의식적으로 담기보다는 의식적으로 담는 것이 효율적
- 이 내용이 결국 서비스가 내재적으로 담게될 가치가 될 것
- 함께 비즈니스를 할 사람들의 삶의 맥락을 느껴서 커뮤니케이션의 효율을 높임

### cf) 저장 위치 
01. 팀빌딩 > 170517_시작 동기와 관련된 에세이 작성

**Comment by DaylightOwl** [comment]
수진님 (@SlowsooSlow), 제가 Issue Body에 작성한 주제 명확화 해서 수정해 주세요!

**Comment by DaylightOwl** [comment]
에세이는 아래의 경로에 저장
01. 팀빌딩 > 170517_시작 동기와 관련된 에세이 작성

**Comment by wonmipark** [comment]
### 이 프로젝트에 원미님이 참여한 이유
#### 나는` 왜 이 일을 하고 있을까?

“이게 다 외로워서 그래.”

농담처럼 주고받던 이 문장이 시작이었다. 이게 다 사람들이 외로워서 그렇다.
우리 사회는 왜 이렇게 남의 시선을 의식할까? 우리는 왜 서로에게 늘 날을 세우고 있을까? 우리는 왜 이렇게 비슷한 인생들을 살고 있을까? 우리는 왜...

우리는 모두 누군가와 관계를 맺고 살아간다. 그러나 내가 속한 집단에서 소외된다면 나는 외로워진다. 그렇다면 우리는 집단 구성원들에게 미움 받지 않기 위해 그들과 비슷하게 행동하고, 그들이 내릴 나에 대한 평판을 신경써야한다. 그렇게 비슷한 모습으로 살아간다. 하지만 나도 이 집단의 구성원인데 왜 나만 눈치를 봐야하지? 누가 나를 무시하거나 깔보지는 않을까? 이런 생각들은 우리를 지치게 만든다. 심지어 내가 살고 있는 삶이 내면에 숨겨진 나의 욕망과 다른 삶이라면, 어느 날 우리에게 삶이 버거워지는 순간이 찾아온다. 삶은 놓치고 적대적으로 반응함으로써 남겨진 내 삶을 지키고자 한다. 그래, 이게 다 외로워지고 싶지 않아서, 이미 외로워 져서 생기는 일이다. 

#### 그렇다면 나는?

내 인생을 생각 해 본다. 나는 외롭지 않은가? 매우 행복하게도, 지금 이 순간 나의 대답은 No. 나는 내 삶의 중요한 가치들을 잘 지켜가면서 나름 만족스러운 삶을 살고 있다.

나는 내 중심이 상당히 강한 사람이다. 그리고 내가 매우 중요하게 여기는 가치는 다양성이다. 각자 다른 세계가 서로 공존하는 상태를 지향한다. 하지만 나의 이상향은 독립된 세계가 혼합물로 그저 섞여있는 상태를 말하는 것은 아니다. 서로 영향을 주고받으며 변할 수 있지만 그 와중에 각자의 세계가 공존하는 상태이다. 그래서 나는 많은 사람들과 대화하고 그 대화 속에서 새로운 무언가를 학습하고, 그 결과 나의 세계를 계속 수정하면서 더 나은 삶을 살아가고 나로 인해 나와 관계 맺은 타인의 삶도 좀 더 나아지고 변화하기를 바란다.

그래서 커뮤니티와 학습에 주목한다. 나와 다른 세계가 충돌하면서 새로운 무언가를 발견하기도 하고, 때로는 변화한다. 나와 다른 세계를 이해하고 존중하며 공존한다. 이를 가능하게 하는 방법은 대화와 경청이다. 나는 지금까지 많은 좋은 사람들과 대화하며 나의 세계를 변화시켜 나갔고, 나와 다른 세계를 이해하고 함께하고자 노력했다. 그래서 내 중심을 지킬 수 있었고 외롭지 않았다.

내 방식이 정답은 아니다. 하지만 이 삶의 방식을 통해 나는 외롭지 않게 되었다. 이 방법이 누군가에게 도움이 된다면, 나는 세상을 조금 더 행복하게 만들 수 있지 않을까? 내가 외롭지 않게 살아 온 방법을 공유하기 위해 이 일을 시작 해 보려고 한다. 


### 이 글에 대한 카톡QNA
Q. '서로 영향을 주고받으며 변할 수 있지만 그 와중에 각자의 세계가 공존하는 상태이다'를 좀 더 자세히 설명한다면? 
A. 이게 틀리네 맞네는 각자 판단하고 나는 이렇게 생각한다 / 니가 생각하는 이거에 대해 나는 다르게 요래요래 생각한다. 까지 이야기 합니다. 그러니까 니가 틀렸어. 라는 표현은 하지 않고. 근데 또 그렇게 이야기를 하다보면 자기 입장도있지만 왜 쟤가 저렇게 생각하나 이해(납득말고)하는 부분도 생기고 실제로 굉장히 실천적인 부분에서는 서로 공유하는 지점들도 생기고. 하지만 성향 자체는 크게 변하지 않더군요. 그래도 공존은 할 수 있음 ㅋㅋㅋ 일단 너 이거 틀림. 지적질만 안해도 ㅋㅋㅋㅋㅋㅋㅋㅋ

Q. 일에 대한 원미님의 생각은?
A. .... 실제로 고딩대까지 나의 꿈은 많이 배운 현모양처였다고 한다. ...... 박사까지 공부하고 집에서 살림사는 여자 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 하지만 어린엄마가 되지 못했으니 이길은 망했다. 저는 지금까지 그닥 일에대해서 심각하게 고민을 하지 않았어요. 굉장히 추상적으로 어떤 일을 하고 싶다 라는건 있었지만 그 일이 '직업' '생업'으로의 일이 아니어서 그건 지금부터 고민을 좀 해봐야할것 같아요.
약간 아티스트처럼 비효율적으로 일하는데 로망이 있습니다. 끊임없는 토론. 우리는 왜 이 일을 해야 하는가를 회의의 80%쯤 쓰고 20%는 후다닥 해치운다.

### 원미님에 대해 발견해 낸 것
- 영향을 주고 받으며 변할 수 있지만, 그 와중에 각자의 세계가 공존한다. (원미님과 원미 아버님의 관계)
- '왜'의 중요성을 아는 사람이다. 
- 즐거운 생업이 중요하다.

**Comment by SlowsooSlow** [comment]
### 이 프로젝트에 수진님이 참여한 이유

**내 삶의 '결'과 잘 맞는다**

고등학교 때, 인생 계획표 같은 걸 가정 시간에 그렸는데, 그때 내가 그린 것은 30대 후반에 사회적으로 크게 성공한 뒤, 40대에 입적하고 50대에 열반에 드는 것이었다. 그리고 그 모든 것을 사람들과 나눈다는 내용이었다. 저런 걸 그린 이유는 산다는 것에 의미가 뭘까를 중고등학교 내내 사고한 결과 내린 유치한 결론이었는데. 돌이켜 생각해보면 서른이 넘은 지금에 와서도 저 생각의 결들은 그다지 크게 달라 진 것이 없어 보인다. 

대학교 2학년 때, 너는 지식인이 되고 싶어서 힘들구나 라는 좀 거친 말을 들었을때 맥이 탁 풀렸다. 매사 반골적이고 비판적인 성격, 삶의 본질적인 의미가 무엇인지에 대한 궁금증을 가지고 있고, 내가 사는 세계의 모순들에 대한 의문들을 풀어 내고자 하고, 그리고 그 길에 다른 모두와 함께 가고 싶다는 소망. 그래서 나는 책을 열심히 읽고 열심히 뭐든 깨달으려고 애썼다. 그리고 사람들과 나누고 싶었다. 우리들의 비밀을!

대학을 졸업하고 취업을 했을때, 밝혀낸 소소한 비밀들을 회사 일에 풀어보려고 했다. 서비스에 녹여보고자 했다. 하지만 그런 입장이 회사에서는 되려 욕심이 되어버리곤 했다. 설득도 어려웠다. (하지만 회사에 진정 도움이 되었을 것이라는 믿음은 여전히 변치 않았다.) 그리고 때로 회사에선 그런 태도가 일 진행에 해가 될 때도 있다는 것도 배웠다. 그래서 그 태도들과 거리를 두고, 회사 일을 열심히 해보려 했다. 하지만 그럴 수록 중요한 뭔가가 쪼그라 든다는 느낌을 받았다. 성장이 멎었고, 불행했고 일을 하는 시간 시간들이 후회스러웠다. (그리고 깊어지는 불면증)

그래서 나한테는 이 프로젝트가 귀하다. 이 프로젝트로 지금 내 또래의 친구들에게 알맞은 질문을 던질 수 있을 것 같기 때문이다.(이건 내 꿈이기도 하고) 우리가 좋아하는 것들의 비밀을 함께 밝히다 보면 - 예를 들면 우리는 왜 혼밥/혼술/혼잠을 하는가. 우리가 좋아하는 것들은 무슨의미를 가지는가. 크래프트비어, 협소주택 등이 인기있는 이유는 뭘까. 무엇에 열광하고 어떻게 살고 있나. 우리는 어떻게 돈을 벌고 쓰고 향유해야 행복해지는가- 다함께 행복해 질 길을 구체적으로 찾게 될 것이라고 믿기 때문이다. 거기다 그것을 공부, 놀이, 여행, 비즈니스 모델 찾기로 만들어 내는 것이라니! 아주 실제적이어서 더욱 안성맞춤이다. 그래서 꼭 성취해보고 싶다. 1조짜리 비즈니스. (결국 액수란 사람들의 시간에 그 만큼 기여했다는 뜻일테니. 액수가 아주 중요하다.)

**좋아하는 것의 역사**

나는 내가 좋아하는 사람들을 통해서, 좋아하는 것의 감각을 넓혀왔다. 소설을 읽을 수 없었던 내가 소설을 읽게 된 것은, 그걸 좋아하는 친구를 좋아했기 때문이었다. 그가 좋은데, 왜 좋은지를 몰라서, 그 친구를 이해해 보고 싶고, 더 가까워 지고 싶고, 닮고 싶고, 더 친해지고 싶어서 소설을 좋아하게 됐다.

생각하면 영국밴드는 S가, 락페는 Y가, 2차창작과 아이돌은 P가, 돈은 M이. 나는 뭐든 사람을 먼저 좋아하고 그 다음에 자연스럽게 그 사람들이 좋아하는 것들을 내식대로 좋아하게 됐던 것 같다. 하지만 이 방법만 또 있었던 건 아닌 것 같다. 하울의 움직이는 성을 보다가 일본 애니메이션에 빠져들었고, 우연한 공연으로 갤럭시익스프레스를, 밥벌이의 지겨움을 읽다가 김훈이라는 사람에 빠져들었었고, 데미안을 보다가 헤르만헤세를, 불교를, 세계문학을 좋아하게 됐다.

재밌는 점은 이런 부분의 감각들이 변하면서 ‘사고방식과 가치관이 조금씩 변해왔다’는 것이다. 큰 폭에선 외적인 성취지향의 반작용으로 내적인 것에 몰입하는  방향, 내적인 것에 대한 지향은 또 다시 물질에 대한 열등감을 낳았고 그리고 또 다시 물질을 이해하고 성취하려는 방향, 그리고 다시 내적인 것과 통합하는 방향. 그러니까 저런 구체적인 좋아하는 것들을 몸으로 받아들이면서 보이지 않는 사고관과 관점들이 조금씩 깨지면서 통합되었고, 외부에서는 느끼지 못했을 지라도, 스스로는 조금씩 살기 나아졌고 무르익어 왔다.

그래서 나는 좋아하는 것이 베이는 것으로서 나는 사람들의 삶의 질이 바뀌길 바란다. 생활방식을 넓히고, 그럼으로써 관점을 깊게 만들어주는 것이었으면 한다. 자신이 지향하는 것을 알고 그것을 즐겁게 바꾸는 경험, 친구라는 아주 작은 실마리에서부터 가치관을 흔들기까지라는 경험했던 우주의 작은 맛을 이 서비스에 녹여보고 싶다. 


**나의 입장들**

일에 대한 입장은 이렇다. 일에 그 사람의 운명이 깃들 때, 다른 사람들의 마음(=우주)은 반드시 응답한다. 그래서 일을 할 때 내 운명과 이 일이 합치하는 지를 늘상 살핀다. 그게 잘 맞을 때는 일이 잘 풀리고, 그게 어긋날 때는 일이 어그러진다. 회사를 다니니, 내 운명을 억지로 꿰어야 하는 일이 는다. 별로 좋지 않다는 것을 알지만, 그 다음 일을 모색하기 위해서는 지금의 회사를 다니는 것이 어쩔 수 없었다.(학자금 대출 상환, 원룸전세값, 업무능력 등) 때문에 함께 일을 할 사람들의 운명에도 깊은 관심이 있다. 

지금 시대에 대한 입장은 이렇다. 지금 시대의 사람들이 외로운 이유는 ‘우주’와 단절되었기 때문이다. 사실은 연결되어 있지만, 그 연결되어 있다는 것을 모종의 이유로 잊게 되었기 때문이다. 그 모종의 이유는 미니멀리즘을 강조하는 세태랑도, 자본이 전부라는 세태랑도, 중세(종교, 가문, 계급사회)를 벗어나기 위해 사람들의 기울였던 사람들의 분투와도 관계가 깊다. 그리고 그 잊어버렸던 것을 다시 회복하는 것에서-우주와 연결되어 있음을 깨닫고 호기심을 기울이는 데서- 외로움이 사라진다. 이런 믿음 같은 걸 가지고 있다. 

내 세대에 대한 입장은 이러하다. ‘우주’와 단절된 세대에 의해 길러 졌으나 우주를 갈구하는 세대. 돈이 전부가 아님을 알지만 돈에 의존하는 세대. 새 길을 찾고 싶어하지만 새 길이 무엇인지는 모르는 세대. 떳떳하게 산다는 것을 처음으로 경험하기 시작한 세대 하지만 스스로의 시대를 짓고 있지는 못한 세대. 본질적으로 사유하는 것을 아직 배워보지 못했지만 배우려는 의지는 생성되고 있는 세대. 

이 흐름에서 원미님, 호철님과 '좋아하는 것'의 단서를 바탕으로 사람들이 진정 외로워지지 않는 ‘공부’와 ‘여행’, 새로운 삶의 '방식'을 함께 짓는 서비스를 만들고 싶다. 그래서 우리 세대의 색을 세상에 내보고 싶다. 새로운 시대에의 제안.

**Comment by DaylightOwl** [comment]
대학원에 입학해서 가장 많이 받는 질문은, '왜 이곳에 입학했습니까?' 였다. 나의 대답은 언제나 같았다. **'교육으로 세상을 더 좋게 만드는 방법을 찾고 싶기 때문입니다.' 누군가의 성장에 긍정적인 영향을 주는 것은 그때의 나에게 아주 중요한 의미를 가지고 있었다. 나는 나의 방법으로 세상에 긍정적인 변화를 만들고 싶었다.**

나는 변화를 만들고 싶었지만 대학원에서 연구를 하는 내내 생존을 고민해야 했고, 또 **나는 너무나도 현실주의자**였다. 그래서 결국 나는 내가 이야기 했던 'Why'를 스스로 흔들었다. 그 다음은 흔한 이야기이다. 연구는 애초의 나의 목적에서 조금씩 거리가 생겼고, 결국 타협하듯, 학자금 대출을 갚겠다는 이유로 여기까지 와 버렸다. 물론 그 와중에 많은 운이 따라주었기 때문에 여기까지라도 오게 되었다. 



지금의 나는 교육으로 세상을 더 좋은곳으로 바꾸겠다는 생각을 더 이상 하지는 않는다. **그 소명은 내 몫이 아니라는 판단을 내린지 이미 오래다. 그 자체의 가능성 문제도 있지만, 그것을 내가 할 수 있는가를 가늠해 본다면 나는 그럴 능력이 부족한 사람**이다. 하지만 나에게, **세상을 더 좋은 곳**으로 만들어야 한다는 생각은 여전히 유효하다. 

2년 전 쯤 이었나보다. 방 안 침대에서 미드 '뉴스룸'을 보고 있던 나는 상실감에 사로잡혔다. 언론사가 배경이었던 그 드라마에서는 언론인으로서 소명의식을 가진 사람들이 모여 고민하고, 행동하고, 싸우고, 좌절하고, 아주 가끔 기뻐하고 있었다. 각자가 가진 당위성 안에서 나름의 치열함을 가지고 움직이는 드라마 속 사람들. 그 사람들을 보던 중 돌아본 나는 얼마나 초라하던지.

큰 회사 연구원이 된 나에게 내가 오랜 시간동안 떠안고 있던 많은 불확실성은 이제 낯선 존재가 되었다. 최근의 나는 비싼 구구콘도 거리낌없이 먹고, 뱅쇼도 아무 생각없이 틈만 나면 사 마시고 있다. 지금의 포지션이 쥐도새도 모르게 사라질까 예전만큼 걱정하지 않는다. 사실 나는 편하자면 끝도없이 편할 수 있는 영역에 지금 서 있는 것이다. 하지만 나는, 5년 전 왜 대학원에 입학했는가를 설명하던 그 때보다 초라한 사람이다.

그래서 나는 계속해서 스스로에게 질문을 던졌다. '내가 할 수 있는, 세상을 더 좋은 곳으로 만들 수 있는 방법은 무엇일까?' 그리고 작년이 끝나갈 무렵, 구체적이지는 않지만 나름의 답을 만들었다. 세상을 더 좋은곳으로 만들기 위해 움직이는 사람, 혹은 그런 팀을 찾아 그것이 가능할 수 있는 방법을 함께 고민하고 싶다. 내 능력을 덧붙여 그것이 가능할 수 있도록 만들고 싶다. 그런 일을 할 때, 나에게 여전히 유효한 당위성을 다시 이어갈 수 있겠다고 생각했기 때문이다.

여기까지가 17년 1월의 글이다. 

위의 글을 쓸때까지만 해도 나는 세상을 더 좋은 곳으로 만드는 플레이어 역할을 한다고 생각하지 않았다. 벤처 투자자, 혹은 엑셀러레이터가 되어야겠다고 마음먹은 후에 쓴 글이기 때문에 나는 나의 역할을, '세상을 더 좋은 곳으로 만들기 위해 움직이는 사람, 혹은 그런 팀을 찾아 그것이 가능할 수 있는 방법을 고민하는 것'으로 정의 했다. 하지만 플레이어가 되기로 생각한 지금, 내가 만들었던 정의는 여전히 추상적이다.

그래서 다시 고민한다. **좋은 세상이란 무엇일까? 세상의 여러 당위가 있겠지만, 나는 '사람이 파편화 되어있지 않은 곳'이라고 정의**하고 싶다. 생각해보면 세상의 많은 문제들은 개인이 '외롭기' 때문에 생겨난다. 사람 사이의 건강한 유대감을 갖지 못한 사람은 그것의 반작용을 가지게 된다. 그 반작용이 표면에 드러날 수도, 아닐수도 있지만 그것이 만드는 부정적인 영향은 명백하다. 

그러므로 사람이 모일 수 있는 플랫폼이 필요하다는 생각을 한다. 그러나 그 플랫폼은 조직된 단체를 의미하거나, 특정한 목적을 갖는 집단을 의미하지는 않는다. **개인이 파편화 되지 않는 것은 중요하지만, 모든 사람은 각자의 의지에 따라 판단하고 움직여야**만 한다. 따라서, 여기서 이야기하는 플랫폼이 사람들에게 특정한 당위나, 목적, 혹은 의지를 제공해서는 안된다.

물론, 사람이 모이는 것 만으로 세상이 좋은곳으로 바뀌지는 않는다. 사람이 모였을 때 모인 사람들은 어떤 에너지를 만들어 낸다. 그 에너지는 혼자서는 만들 수 없는 종류의 것이다. 그런데 그 에너지는 흐르는 방향에 따라 긍정적인 변화를 만들어내기도 하고, 오히려 문제가 만들기도 한다. 결국 내가 필요하다고 했던 플랫폼은, 사람들이 모여 만들어 내는 에너지가 긍정적인 변화로 흐를 수 있게해야 의미가 있다.

그렇다면 왜 비즈니스를 통해 이것을 풀어내려고 하는가? 내가 말하는 플랫폼은  굳이 비즈니스를 통해 만들 필요는 없다. 내 주변의 작은 모임으로도 충분히 실현할 수 있는 일이다. 혹은, 사회 운동으로도 가능한 일이다. 하지만 굳이 비즈니스를 통해 내 생각을 이루고 싶은 이유는 현실주의자로서 내가 가지는 두 가지 생각 때문이다.

**나는 지속가능한 구조**를 만들고 싶다. 좋은 의도로 시작했고 의미있는 성과를 만들어 냈지만 지속가능성을 만들어 내지 못한 사례는 너무 많다. 가장 빈번하게 등장하는 이유는 돈의 문제이다. 내가 사는 세상은 자본을 기반으로 돌아가기 때문에 당연한 현상이다. 세상이 좋아지게 만드는 유의미한 가치를 만들고, 그 가치가 지속적으로 확대될 수 있게 하는 방법으로서 비즈니스를 선택한 것이다.

또 다른 이유는 내 욕망의 문제이다. 고백하자면 **나는 풍족할 정도의 많은 돈을 벌고 싶다.** 내가 살고 있는 세상에서 돈으로 가능한 것이 많다는 것을 나는 너무 잘 알고 있다. 하지만 동시에, 나는 현실만 바라보며 살 수 있는 종류의 사람도 아니다. 세상에 긍정적인 영향력을 미치고 싶은 욕망이 나에게 있다. 나의 상반된 두 욕망을 해결할 유일한 방법은 비즈니스라고 생각한다.

### 이 글을 읽고 떠오른 질문 (by 야생)
#### 서비스의 철학과 연결될 지점이라 궁금한 부분
- 처음에 교육에 대해 관심을 가지게 된 이유가 궁금합니다. (왠지 근원적인 문제의식과 닿아있어 보여요)
ㄴ하자 센터에 보내놓고 대학에 가라고 함. (4~5만원) 대안교육의 허술함. 
ㄴ하자 센터에서 기획을 하는 게 재밌었음. 
ㄴ학교 말고도 다른 세상이 있구나. 학교에 겉돌았음. 하자센터도 겉돔. 
ㄴ대학에서도 굉장히 답답했었음. 
ㄴ과외. 성당에서 아이들을 가르쳤음. (교육 프로그램 만드는 것)
ㄴ지식 교육을 싫어했음. '실제로 아이들의 개별적인 상황'에 맞는 교육.
ㄴLearning Science. 대안 교육에 대한 방향성 제시.  
ㄴ생존할 수 있는 방법을 알려줘야 한다. (밥짓기, 바느질)
ㄴ본인이 지향하는 것으로 다가갈 수 있는 학습 방법을 알려주는 것이 있어야 함. 
- 두 번째 문단 현실주의자에 대한 정의가 궁금합니다.
ㄴ이상주의가 '현실'이 없으면 무너지는 걸 많이 봄. 
ㄴ생존(실제로 생활을 할 수 없게 되는 상황)에 대한 강박이 있음. 
ㄴ 문화적 생존에 대한 욕구가 있음. 
- 호철님의 주요키워드. 
ㄴ 아나키즘. : 집단주의 배격. 인디비주얼이 가진 모순성. 파편화되는 것은 모순이라 생각함.  
ㄴ 불안. : 가능하면 풍족한 삶을 살고 싶다. >> 다른 사람들도 함께. / 긍정적인 영향. 
ㄴ 교육. : 학교가 가지고 있었던, 집단이 가지고 있는. 우리는 결국엔 연대해서 살아가야 한다고 생각한다. 욕망. 
- 초라하지 않은 삶을 하나의 단어로 표현할 수 있나요?

#### 비즈니스와 연결될 지점이라 궁금한 부분
- 파편화되어 있지 않고, 각자의 의지에 따라 움직인 비슷한 사례가 혹시 있으셨나요?
- 사람들이 파편화되게 만드는 요인과 각자의 의지에 따라 움직이지 못하는 까닭은?
- 파편화되어 있지 않고, 각자의 의지대로 살아간다면, 우리사회에 어떤 좋은 일이 구체적으로 생길까요?
- 80년대생에 대한 생각이 궁금합니다.

**Comment by DaylightOwl** [comment]
결과물 정리를 위해 위의 에세이는 구글 공유 폴더에 저장합니다.

-경로: 01. 팀빌딩 > 1705_에세이 작성 > 팀 빌딩을 위한 에세이 작성 #1. 왜 이 비즈니스를 시작했는가?.doc

**Comment by SlowsooSlow** [comment]
## 1. To-do List
### 정리해 볼 지점.
- [ ] 세 명 플레이어의 강점과 약점, 보완점.
- [ ] 각자 삶의 문제 의식. 세 명이 만나게 된 의미.
- [ ] 우리가 하게 될 비즈니스의 문제의식.
- [ ] 비즈니스의 대상. (어떤 사람들이 이 문제의식과 맞닿아 타겟될 지.)

### 도출할 산출물
- [ ] 슬로건/컨셉/문제의식.
- [ ] 문제의식 해결방법. 
- [ ] 비즈니스 사이즈.

## 2. 정리하기
### 1) 세 명 플레이어의 강점과 약점, 상호 보완점.
- 호철 : 몸  
- 원미 : 왜
- 수진 : 정신
- 웹개발자 / 디자이너. 

### 2) 각자 삶의 문제의식. 
- 호철 : 하고 싶은 일에 대한 꿈(네트워킹).  
- 원미 : 커리어에 대한 고민.
- 수진 : 하고 싶은 일에 대한 꿈. 
- 학자금 대출. / 내 미래에 대한 희망적임에 따라 집/차를 삼. 

### 3) 우리가 하게 될 비즈니스의 문제의식.
- 외로움(여기에 대한 합의된 정의가 있어야 함).
  - 하고 싶은 일을 하지 못한다.
- 모임, 공부, 여행으로 승화.(?)
- 고민을 나눌 친구가 필요하다.

### 4) 비즈니스의 대상. 
- 91년생~83년생 회사를 다니는 사람의 취미 지갑?

## 3. 산출물
### 1) 슬로건/컨셉/문제의식
- 슬로건 : 친구와 함께 떠나는, 세상 모든 것들과의 지적 연애. 
- 컨셉 : 회사원의 학교?
- 문제의식 : 친구와 함께 하는 공부만이 외로움을 진정으로 해갈할 수 있다?

### 2) 문제의식의 해결방법
- 모임
- 공부
- 여행

### 3) 비즈니스의 사이즈
